name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          python-version: 3.14
          cache-python: "true"

      - name: Ruff format
        run: |
          uv tool run -q ruff format --diff 2>format.stderr.txt 1> format.stdout.txt

      - name: Ruff lint
        run: |
          uv tool run -q ruff check --statistics 2>stats.stderr.txt 1>stats.stdout.txt
          uv tool run -q ruff check 2>check.stderr.txt 1>check.stdout.txt

      - name: Summary
        if: success() || failure()
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<EOF
          # Ruff Format Output
          $(cat format.stderr.txt)
          <details>
            <summary>Details</summary>
            $(cat format.stdout.txt)
          </details>
          EOF

          cat >> $GITHUB_STEP_SUMMARY <<EOF
          # Ruff Lint Output
          $(cat stats.stdout.txt)
          <details>
            <summary>Details</summary>
            $(cat check.stdout.txt)
          </details>
          EOF

